version: 2

jobs:
  build:
    docker:
      - auth:
          password: $DOCKER_PASS
          username: $DOCKER_USER
        image: circleci/node:9
    steps:
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
  test:
    docker:
      - auth:
          password: $DOCKER_PASS
          username: $DOCKER_USER
        image: circleci/node:9
    steps:
      - checkout
      - run:
          name: "test"
          command: |
              ./test.sh
  deploy:
    docker:
      - auth:
          password: $DOCKER_PASS
          username: $DOCKER_USER
        image: circleci/node:9
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: 'docker version'
      - deploy:
          command: |
            printenv DOCKER_PASS | docker login -u ${DOCKER_USER} --password-stdin
            ./build-images.sh 11
            ./build-images.sh 14
            ./release_images.sh 11
            ./release_images.sh 14
    working_directory: ~/fdk-node
workflows:
  commit:
    jobs:
      - build
      - test
      - deploy
  version: 2
