version: 2

jobs:
  deploy:
    docker:
      - auth:
          password: $DOCKER_PASS
          username: $DOCKER_USER
        image: circleci/node:9
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: 'docker version'
      - deploy:
          command: |

            ./build-images.sh 11
            #./build-images.sh 14
            #./release_images.sh 11
            #./release_images.sh 14
    working_directory: ~/fdk-node
workflows:
  commit:
    jobs:
      - deploy
  version: 2
