version: 2.1
orbs:
  anchore-engine: anchore/anchore-engine@1.2.0
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/go/src/github.com/fnproject/fdk-node
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
      - checkout
      - run:
          command: |
            sudo npm install -g snyk
      - run:
          name: "test"
          command: |
              npm install
              npm run test
      - deploy:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" && -z "${CIRCLE_PR_REPONAME}" ]]; then
              # todo: login to npm
              git config --global user.email "ci@fnproject.com"
              git config --global user.name "CI"
              git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
              ./release.sh
              rm -f .npmrc
              ./build-images.sh 8
              ./build-images.sh 10
              ./build-images.sh 11
              ./release_images.sh
            fi
  local_image_scan:
    executor: anchore/anchore_engine
    working_directory: ~/go/src/github.com/fnproject/fdk-node
    steps:
      - checkout
      - run:
          name: Node.JS 8 build
          command: |
            ./build-images.sh 8
      - anchore/analyze_local_image:
          image_name: fnproject/node:8-dev
          timeout: '500'
          analysis_fail: True
      - anchore/analyze_local_image:
          image_name: fnproject/node:8
          timeout: '500'
          analysis_fail: True

      - run:
          name: Node.JS 10 build
          command: |
            ./build-images.sh 10
      - anchore/analyze_local_image:
          image_name: fnproject/node:10-dev
          timeout: '500'
          analysis_fail: True
      - anchore/analyze_local_image:
          image_name: fnproject/node:10
          timeout: '500'
          analysis_fail: True

      - run:
          name: Node.JS 11 build
          command: |
            ./build-images.sh 11
      - anchore/analyze_local_image:
          image_name: fnproject/node:11-dev
          timeout: '500'
          analysis_fail: True
      - anchore/analyze_local_image:
          image_name: fnproject/node:11
          timeout: '500'
          analysis_fail: True
