version: 2
jobs:
  build:
    working_directory: ~/fdk-node
    machine:
      image: ubuntu-1604:202101-01
    steps:
      - checkout
      - run:
          name: Update Docker to latest
          command: ./.circleci/install-docker.sh
      - run: 'docker version'
      - run:
         name: Login to Docker
         command: |
              docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
         name: print env
         command: |
               printenv DOCKER_USER
      - deploy:
          command: |
            ./build-images.sh


